#!/bin/sh

REPOS="flavors flavors-stable libtaz slitaz-base-files \
 slitaz-boot-scripts slitaz-configs slitaz-doc slitaz-forge \
 slitaz-pizza slitaz-tools tank tazchroot tazlito tazpkg tazusb \
 tazwok tazwok-experimental website wok wok-stable wok-tiny \
 wok-undigest"
WWW="tank hg pkgs bb doc website people"
BASE_IP="127.0.0"
END_IP="1"
#ADDRESS="local.www local.tank local.hg local.bb local.people"
ADDRESS="www.slitaz.org tank.slitaz.org pkgs.slitaz.org hg.slitaz.org bb.slitaz.org people.slitaz.org"
#VHOST_FILE="/etc/lighttpd/vhosts-local.conf"
VHOST_FILE="/etc/lighttpd/vhosts-localnet.conf"
REPOS_DIR="/home/slitaz/repos"
WWW_DIR="/home/slitaz/www"

if [ "$1" = "network" ]; then
	BASE_IP="192.168.1"
	END_IP="110"
	ADDRESS="www.slitaz.org tank.slitaz.org hg.slitaz.org bb.slitaz.org people.slitaz.org"
	VHOST_FILE="/etc/lighttpd/vhosts-localnet.conf"
fi

[ -d $REPOS_DIR ] || continue
[ -d $WWW_DIR ] || mkdir -p $WWW_DIR
for b in $WWW; do
    [ -d $WWW_DIR/$b ] && continue
    if [ "$b" = "website" ]; then
		[ -d $REPOS_DIR/$b ] && ln -s $REPOS_DIR/$b $WWW_DIR
	fi
	if [ "$b" = "people" ]; then
		[ -d $REPOS_DIR/slitaz-forge/people ] && ln -sf $REPOS_DIR/slitaz-forge/people $WWW_DIR
	fi
	if [ "$b" = "doc" ]; then
		[ -d $REPOS_DIR/slitaz-forge/doc ] && ln -sf $REPOS_DIR/slitaz-forge/doc $WWW_DIR
	fi
	if [ "$b" = "tank" ]; then
		[ -d $REPOS_DIR/$b/web ] && ln -sf $REPOS_DIR/$b/web $WWW_DIR/$b
	fi
	if [ "$b" = "hg" ]; then
		[ -d $WWW_DIR/hg ] || mkdir -p $WWW_DIR/hg
		[ -f /usr/share/examples/mercurial/hgwebdir.cgi ] && ln -sf /usr/share/examples/mercurial/hgwebdir.cgi $WWW_DIR/hg
	fi
done

for repo in $REPOS; do
	if [ ! -f $REPOS_DIR/$repo/.hg/hgrc-web ]; then
		touch $REPOS_DIR/$repo/.hg/hgrc-web
		echo "[web]" >> $REPOS_DIR/$repo/.hg/hgrc-web
		echo "style = slitaz" >> $REPOS_DIR/$repo/.hg/hgrc-web
		echo "push_ssl = false" >> $REPOS_DIR/$repo/.hg/hgrc-web
		echo "allow_push = *" >> $REPOS_DIR/$repo/.hg/hgrc-web
		[ ! -f $REPOS_DIR/$repo/.hg/hgrc-pull ] && mv $REPOS_DIR/$repo/.hg/hgrc $REPOS_DIR/$repo/.hg/hgrc-pull
		[ ! -f $REPOS_DIR/$repo/.hg/hgrc ] && cp -a $REPOS_DIR/$repo/.hg/hgrc-web $REPOS_DIR/$repo/.hg/hgrc
	fi
	
	if [ ! $(grep -l 'name = ' $REPOS_DIR/$repo/.hg/hgrc ) ]; then
		echo "name = $repo" >> $REPOS_DIR/$repo/.hg/hgrc
	fi
	
	if [ ! $(grep -l 'contact = ' $REPOS_DIR/$repo/.hg/hgrc ) ]; then
		[ "$repo" = "flavors" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "flavors-stable" ] && echo "contact = Pascal Bellard" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "libtaz" ] && echo "contact = Antoine Bodin" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-base-files" ] && echo "contact = Pascal Bellard" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-boot-scripts" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-configs" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-doc" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-forge" ] && echo "contact = Eric Joseph-Alexandre" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-pizza" ] && echo "contact = Pascal Bellard" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-tools" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tank" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tazchroot" ] && echo "contact = Antoine Bodin" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tazlito" ] && echo "contact = Pascal Bellard" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tazpkg" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tazusb" ] && echo "contact = Eric Joseph-Alexandre" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tazwok" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "website" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "wok" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "wok-stable" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "wok-tiny" ] && echo "contact = Pascal Bellard" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "wok-undigest" ] && echo "contact = Christophe Lincoln" >> $REPOS_DIR/$repo/.hg/hgrc
	fi
	
	if [ ! $(grep -l 'description = ' $REPOS_DIR/$repo/.hg/hgrc) ]; then
		[ "$repo" = "flavors" ] && echo "description = SliTaz Cooking flavors" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "flavors-stable" ] && echo "description = SliTaz Stable flavors" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "libtaz" ] && echo "description = SliTaz shared libraries" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-base-files" ] && echo "description = SliTaz base files" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-boot-scripts" ] && echo "description = SliTaz boot scripts" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-configs" ] && echo "description = SliTaz configuration files" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-doc" ] && echo "description = SliTaz system doc" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-forge" ] && echo "description = SliTaz Forge Config" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-pizza" ] && echo "description = SliTaz Online flavor builder" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "slitaz-tools" ] && echo "description = SliTaz Tools and Tinyutils" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tank" ] && echo "description = SliTaz main server tools/vhost" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tazchroot" ] && echo "description = SliTaz chroot manager" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tazlito" ] && echo "description = SliTaz Live Tool" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tazpkg" ] && echo "description = SliTaz Packages manager" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tazusb" ] && echo "description = SliTaz LiveUSB utility" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "tazwok" ] && echo "description = Slitaz Packages builder" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "website" ] && echo "description = SliTaz Website" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "wok" ] && echo "description = SliTaz Cooking wok" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "wok-stable" ] && echo "description = SliTaz Stable wok" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "wok-tiny" ] && echo "description = Tiny SliTaz wok" >> $REPOS_DIR/$repo/.hg/hgrc
		[ "$repo" = "wok-undigest" ] && echo "description = SliTaz Undigest wok" >> $REPOS_DIR/$repo/.hg/hgrc
	fi
done

for hostname in $ADDRESS; do 
	END_IP=$(($END_IP+1))
	for i in $END_IP; do
		if [ ! $(grep -l "${BASE_IP}.$i $hostname" /etc/hosts) ]; then
			echo "${BASE_IP}.$i $hostname" >> /etc/hosts
		fi
	done 
done

[ -f $VHOST_FILE ] && ln -sf $VHOST_FILE /etc/lighttpd/vhosts.conf
